export const COMMUNICATION_ERROR_CODES = {
  INVALID_REQUEST: 'COMMUNICATION_INVALID_REQUEST',
  TEMPLATE_NOT_FOUND: 'COMMUNICATION_TEMPLATE_NOT_FOUND',
  TEMPLATE_RENDER_FAILED: 'COMMUNICATION_TEMPLATE_RENDER_FAILED',
  RECIPIENT_UNREACHABLE: 'COMMUNICATION_RECIPIENT_UNREACHABLE',
  PROVIDER_NOT_REGISTERED: 'COMMUNICATION_PROVIDER_NOT_REGISTERED',
  PROVIDER_CONFIGURATION_INVALID:
    'COMMUNICATION_PROVIDER_CONFIGURATION_INVALID',
  PROVIDER_REJECTED: 'COMMUNICATION_PROVIDER_REJECTED',
  PROVIDER_UNAVAILABLE: 'COMMUNICATION_PROVIDER_UNAVAILABLE',
  DELIVERY_EXPIRED: 'COMMUNICATION_DELIVERY_EXPIRED',
  DELIVERY_CANCELLED: 'COMMUNICATION_DELIVERY_CANCELLED',
  RETRY_EXHAUSTED: 'COMMUNICATION_RETRY_EXHAUSTED',
} as const;

export type CommunicationErrorCode =
  (typeof COMMUNICATION_ERROR_CODES)[keyof typeof COMMUNICATION_ERROR_CODES];

export class CommunicationError extends Error {
  constructor(
    public readonly code: CommunicationErrorCode,
    message: string,
    public readonly retryable: boolean = false,
    public readonly metadata?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'CommunicationError';
  }
}
